Return error message as `str` instead of `print`ing message
- `raise ValueError()` expects a `str`, so `print`ing the message results in the message appearing ABOVE the stack trace and error message
  - this is not intuitive (and also an incorrect way to `raise` exceptions)

```
===>ERROR!<===
The url you provided could not be parsed properly. Please check the url you provided to make sure there are no typos!

For further debugging, this was the exact error message (might also be blank):
list index out of range

Traceback (most recent call last):
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 27, in process_url
    _, channel_type, channel_id = parse_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 33, in parse_url
    channel_info = url.split('youtube.com/')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/yt_videos_list/python/yt_videos_list/__init__.py", line 340, in create_list_for
    video_data, write_information = logic.execute(deque([url]), file_name, log_silently, *instance_attributes)
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 229, in execute
    url = process_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 29, in process_url
    raise ValueError(common_message.display_url_error(error_message))
ValueError: None
```

- `return`ing the message as a `str` fixes this output

```
Traceback (most recent call last):
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 27, in process_url
    _, channel_type, channel_id = parse_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 33, in parse_url
    channel_info = url.split('youtube.com/')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/yt_videos_list/python/yt_videos_list/__init__.py", line 340, in create_list_for
    video_data, write_information = logic.execute(deque([url]), file_name, log_silently, *instance_attributes)
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 229, in execute
    url = process_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 29, in process_url
    raise ValueError(common_message.display_url_error(error_message))
ValueError:

===>ERROR!<===
The url you provided could not be parsed properly. Please check the url you provided to make sure there are no typos!

For further debugging, this was the exact error message (might also be blank):
list index out of range

```