Update `save_thread_result` package dependency version number → 0.1.1
- similar reasoning as previous commit
  - read the previous commit message and follow the
    reference to release 0.1.1.post1 (tag `v0.1.1.post1`) in the
    `save-thread-result` for more details
  - starting with python version 3.11, `pip install` no
    longer builds ANY package with a '>=X.Y.*' version modifier
    and only accepts version modifier values of the format '>=X.Y'
  - the `save_thread_result` package also used the incorrect
    '>=X.Y.*' version modifier in all releases up to 0.1.0
    - therefore, installing `save_thread_result` version 0.1.0 fails
    - `save_thread_result` version 0.1.1 fixes the version modifier
      and `save_thread_result` version 0.1.1post1 modifies the version
      modifier from
      `python_requires  = '>3.0, <4'`
      to
      `python_requires  = '>=3, <4'`
      to maintain the same intended semantic requirement as
      all releases up to 0.1.0 (`python_requires  = '>=3.0.*, <4'`)

```
python3.11 -m pip install .
Processing /Users/user/yt_videos_list/python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting selenium<4,>=3.141.0 (from yt-videos-list==0.6.6)
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting save-thread-result==0.1.0 (from yt-videos-list==0.6.6)
  Using cached save-thread-result-0.1.0.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in save-thread-result setup command: 'python_requires' must be a string containing valid version specifiers; Invalid specifier: '>=3.0.*'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```