Halt program execution until page elements load
- addresses the `selenium.common.exceptions.NoSuchElementException` exception mentioned in https://github.com/Shail-Shouryya/yt_videos_list/issues/7#issuecomment-731517083 from Issue https://github.com/Shail-Shouryya/yt_videos_list/issues/7
- easily reproducible
  - change

```
driver.find_element_by_xpath("//yt-formatted-string[@class='style-scope ytd-channel-name']").text
```

  to

```
driver.find_element_by_xpath("//yt-formatted-string[@class='style-scope ytd-channel-namee']").text
```

  (added an extra "e" at the end of the xpath)
  - resulting in

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //yt-formatted-string[@class='style-scope ytd-channel-namee']
```

- essentially, selenium raises this exception when the executing program tries to search for an element that doesn't exist on the page (as in the example above)
- -> OR: program tries to search for an element that DOES exist on the page but searches for the element BEFORE the page finishes loading, similar to the scenario discussed at https://stackoverflow.com/questions/27112731/selenium-common-exceptions-nosuchelementexception-message-unable-to-locate-ele
- adding the wait logic essentially causes the program to time out if the element the program is looking for ("//yt-formatted-string[@class='style-scope ytd-channel-name']") doesn't exist OR hasn't loaded on the page within the time out period (specified to  seconds here):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```