Unpack list to keep function arguments the same (bugfix)
- BEFORE unpacking list, `args` in `log_test_info(message, *args)` was
  - a tuple containing 1 element: a list of 4 `str`s

```
# log_test_info('*' * 140,        log_files)
# args in log_test_info(message, *args) is
(['CoreySchafer_reverse_chronological_videos_list.log', 'CoreySchafer_chronological_videos_list.log', 'CoreySchafer_reverse_chronological_video_ids_list.log', 'CoreySchafer_chronological_video_ids_list.log'],)
```

  - and resulted in the following error when running tests/run_tests.sh:

```
Traceback (most recent call last):
  File "/Users/user/yt_videos_list/python/tests/test_all_drivers.py", line 34, in <module>
    main()
  File "/Users/user/yt_videos_list/python/tests/test_all_drivers.py", line 24, in main
    test_cross_platform_drivers.main()
  File "/Users/user/yt_videos_list/python/tests/test_cross_platform_drivers.py", line 38, in main
    run_tests_for(browsers)
  File "/Users/user/yt_videos_list/python/tests/test_shared.py", line 43, in run_tests_for
    log_test_info('*' * 140,        log_files)
  File "/Users/user/yt_videos_list/python/tests/test_shared.py", line 105, in log_test_info
    with open(log_file, mode='a', encoding='utf-8') as output_location:
TypeError: expected str, bytes or os.PathLike object, not list
```

- AFTER unpacking list (the change in this commit), `args` in `log_test_info(message, *args)` is
  - a tuple containing 4 elements: every element is a `str`

```
# log_test_info('*' * 140,        *log_files)
# args in log_test_info(message, *args) is
('CoreySchafer_reverse_chronological_videos_list.log', 'CoreySchafer_chronological_videos_list.log', 'CoreySchafer_reverse_chronological_video_ids_list.log', 'CoreySchafer_chronological_video_ids_list.log')
```

  - and results in no errors when running tests/run_tests.sh