Avoid `csv_writer` initialization in `program` module
- addresses the following `mypy` errors:

```
mypy --strict --show-error-context --show-column-numbers --show-error-end --pretty --show-absolute-path -p python.dev
/Users/user/yt_videos_list/python/dev/writer.py: note: In function "create_file":
/Users/user/yt_videos_list/python/dev/writer.py:40:13:40:13: error: Name "csv_writer" already defined on line 29  [no-redef]
                csv_writer: csv.DictWriter = csv.DictWriter(temp_file, fieldnames=fieldnames)
                ^
/Users/user/yt_videos_list/python/dev/writer.py:41:13:41:34: error: "None" has no attribute "writeheader"  [attr-defined]
                csv_writer.writeheader()
                ^~~~~~~~~~~~~~~~~~~~~~
/Users/user/yt_videos_list/python/dev/writer.py:43:46:43:55: error: Argument 3 to "create_entries" has incompatible type "None"; expected "DictWriter[Any]"  [arg-type]
            create_entries(file_type, temp_file, csv_writer, logging_locations, identifier, video_data, reverse_chronological, total_videos, number_of_existing_videos=0, file_visited_videos=set())
                                                 ^~~~~~~~~~

/Users/user/yt_videos_list/python/dev/writer.py:83:41:83:88: error: Incompatible types in assignment (expression has type "DictWriter[str]", variable has type "None")  [assignment]
                csv_writer                = csv.DictWriter(temp_file, fieldnames=fieldnames)
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/user/yt_videos_list/python/dev/writer.py:84:39:84:60: error: "None" has no attribute "writeheader"  [attr-defined]
                if reverse_chronological: csv_writer.writeheader() # only write header when reverse_chronological=True since the pre-existing csv file will already contain the header when reverse_chronological=False (and the new v...
                                          ^~~~~~~~~~~~~~~~~~~~~~
/Users/user/yt_videos_list/python/dev/writer.py:91:50:91:59: error: Argument 3 to "create_entries" has incompatible type "None"; expected "DictWriter[Any]"  [arg-type]
                create_entries(file_type, temp_file, csv_writer, logging_locations, identifier, video_data, reverse_chronological, total_videos, number_of_existing_videos, file_visited_videos)
                                                     ^~~~~~~~~~
```