updates "return" -> sys.exit() inside closure function
- returning nothing from inside a closure function when we want to end the program results in returning None to the calling function checkUserInput(), which results in:
TypeError: cannot unpack non-iterable NoneType object
- returning from the main execution context is fine since we just stop executing as soon as we hit "return", but returning from inside a closure function just hands execution off to the calling function and does not end execution, so we need to explicitly stop the program