Raise exception `from` original exception
- https://stackoverflow.com/questions/24752395/python-raise-from-usage
- changes the explanation in the stack trace from
  - During handling of the above exception, another exception occurred:
to
  - The above exception was the direct cause of the following exception:
- full stack trace (previous):

```
Traceback (most recent call last):
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 27, in process_url
    _, channel_type, channel_id = parse_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 33, in parse_url
    channel_info = url.split('youtube.com/')[1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/yt_videos_list/python/yt_videos_list/__init__.py", line 340, in create_list_for
    video_data, write_information = logic.execute(deque([url]), file_name, log_silently, *instance_attributes)
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 229, in execute
    url = process_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 29, in process_url
    raise ValueError(common_message.display_url_error(error_message))
ValueError:
```

- full stack trace (current):

```
Traceback (most recent call last):
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 27, in process_url
    _, channel_type, channel_id = parse_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 33, in parse_url
    channel_info = url.split('youtube.com/')[1]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/yt_videos_list/python/yt_videos_list/__init__.py", line 340, in create_list_for
    video_data, write_information = logic.execute(deque([url]), file_name, log_silently, *instance_attributes)
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 229, in execute
    url = process_url()
  File "/Users/user/yt_videos_list/python/yt_videos_list/logic.py", line 29, in process_url
    raise ValueError(common_message.display_url_error(error_message)) from error_message
ValueError:
```