checks to see if STORED_IN_[TXT|CSV] defined
- if either the txt file or the csv file don't exist, this package would execute file.create_file.scroll_to_bottom() in program.py
  - this means that since file.update_file.scroll_to_old_videos() isn't executed, neither STORED_IN_TXT nor STORED_IN_CSV would be defined since file.create_file.scroll_to_bottom() runs instead of file.update_file.scroll_to_old_videos() in program.py
  - this means both STORED_IN_TXT and STORED_IN_CSV are undefined in the write_to_txt() and write_to_csv() functions, respectively, so the program would crash with the following error:
NameError: name 'STORED_IN_[TXT|CSV]' is not defined

- trying to reassign STORED_IN_[TXT|CSV] in the if/else statement resulted in the following error:
UnboundLocalError: local variable 'STORED_IN_TXT' referenced before assignment
  - worked around by creating a new local variable stored_in_[txt|csv] and
    - assigning the value of STORED_IN_[TXT|CSV] to stored_in_[txt|csv] if STORED_IN_[TXT|CSV] exists (implying file.update_file.scroll_to_old_videos() ran in program.py)
    - otherwise running store_already_written_videos() to create the videos set (implying file.create_file.scroll_to_old_videos() ran in program.py)